# Generated by Django 5.1.12 on 2025-12-09 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_import", "0005_optimize_fileupload_indexes"),
        ("projects", "0032_enhance_fileupload_model"),
        ("tasks", "0057_ocrcharacterextraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AviationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_number", models.CharField(db_index=True, max_length=50)),
                ("event_description", models.TextField(blank=True, default="")),
                ("date", models.DateField(db_index=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("airport", models.CharField(blank=True, default="", max_length=255)),
                (
                    "flight_phase",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "aircraft_registration",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "aircraft_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("crew_composition", models.JSONField(blank=True, default=dict)),
                (
                    "weather_conditions",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aviation_events",
                        to="data_import.fileupload",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aviation_event",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "aviation_event",
            },
        ),
        migrations.CreateModel(
            name="AviationProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threat_mapping", models.JSONField(blank=True, default=dict)),
                ("error_mapping", models.JSONField(blank=True, default=dict)),
                ("uas_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "default_workflow",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("require_uas_assessment", models.BooleanField(default=True)),
                ("auto_calculate_training", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aviation_project",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "aviation_project",
            },
        ),
        migrations.CreateModel(
            name="LabelingItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("threat_management", models.JSONField(blank=True, default=dict)),
                ("threat_impact", models.JSONField(blank=True, default=dict)),
                ("threat_coping_abilities", models.JSONField(blank=True, default=dict)),
                ("threat_description", models.TextField(blank=True, default="")),
                ("error_management", models.JSONField(blank=True, default=dict)),
                ("error_impact", models.JSONField(blank=True, default=dict)),
                ("error_coping_abilities", models.JSONField(blank=True, default=dict)),
                ("error_description", models.TextField(blank=True, default="")),
                ("uas_applicable", models.BooleanField(default=False)),
                ("uas_management", models.JSONField(blank=True, default=dict)),
                ("uas_impact", models.JSONField(blank=True, default=dict)),
                ("uas_coping_abilities", models.JSONField(blank=True, default=dict)),
                ("uas_description", models.TextField(blank=True, default="")),
                (
                    "calculated_threat_topics",
                    models.JSONField(blank=True, default=list),
                ),
                ("calculated_error_topics", models.JSONField(blank=True, default=list)),
                ("calculated_uas_topics", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aviation_labeling_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labeling_items",
                        to="aviation.aviationevent",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_labeling_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "aviation_labeling_item",
                "ordering": ["event", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="LabelingItemPerformance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labeling_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_links",
                        to="aviation.labelingitem",
                    ),
                ),
            ],
            options={
                "db_table": "aviation_labeling_item_performance",
            },
        ),
        migrations.CreateModel(
            name="ResultPerformance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("severity", models.CharField(blank=True, default="", max_length=50)),
                ("training_topics", models.JSONField(blank=True, default=list)),
                ("training_goals", models.TextField(blank=True, default="")),
                ("recommendations", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aviation_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_performances",
                        to="aviation.aviationproject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_result_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labeling_items",
                    models.ManyToManyField(
                        related_name="result_performances",
                        through="aviation.LabelingItemPerformance",
                        to="aviation.labelingitem",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_result_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "aviation_result_performance",
            },
        ),
        migrations.AddField(
            model_name="labelingitemperformance",
            name="result_performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labeling_item_links",
                to="aviation.resultperformance",
            ),
        ),
        migrations.CreateModel(
            name="TypeHierarchy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("threat", "Threat"),
                            ("error", "Error"),
                            ("uas", "UAS"),
                            ("flight_phase", "Flight Phase"),
                            ("management", "Management"),
                            ("impact", "Impact"),
                            ("coping", "Coping"),
                            ("severity", "Severity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("code", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=255)),
                ("label_zh", models.CharField(blank=True, default="", max_length=255)),
                ("training_topics", models.JSONField(blank=True, default=list)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="aviation.typehierarchy",
                    ),
                ),
            ],
            options={
                "db_table": "aviation_type_hierarchy",
                "ordering": ["category", "level", "display_order"],
                "unique_together": {("category", "level", "code")},
            },
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="error_type_l1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_error_l1",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="error_type_l2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_error_l2",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="error_type_l3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_error_l3",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="threat_type_l1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_threat_l1",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="threat_type_l2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_threat_l2",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="threat_type_l3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_threat_l3",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="uas_type_l1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_uas_l1",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="uas_type_l2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_uas_l2",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="uas_type_l3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeling_items_uas_l3",
                to="aviation.typehierarchy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labelingitemperformance",
            unique_together={("labeling_item", "result_performance")},
        ),
        migrations.AlterUniqueTogether(
            name="labelingitem",
            unique_together={("event", "sequence_number")},
        ),
    ]
