# Generated by Django 5.1.12 on 2025-11-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aviationannotation",
            new_name="aviation_an_annotat_b6722e_idx",
            old_name="aviation_an_annotat_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationannotation",
            new_name="aviation_an_threat__67b3a4_idx",
            old_name="aviation_an_threat__idx",
        ),
        migrations.RenameIndex(
            model_name="aviationannotation",
            new_name="aviation_an_aircraf_81fe32_idx",
            old_name="aviation_an_aircraf_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationdropdownoption",
            new_name="aviation_dr_categor_29f08b_idx",
            old_name="aviation_dr_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationdropdownoption",
            new_name="aviation_dr_parent__5e96b4_idx",
            old_name="aviation_dr_parent__idx",
        ),
        migrations.RenameIndex(
            model_name="aviationdropdownoption",
            new_name="aviation_dr_categor_73288f_idx",
            old_name="aviation_dr_categor_active_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationincident",
            new_name="aviation_in_task_id_8f5840_idx",
            old_name="aviation_in_task_id_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationincident",
            new_name="aviation_in_event_n_a8b076_idx",
            old_name="aviation_in_event_n_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationincident",
            new_name="aviation_in_date_fe6338_idx",
            old_name="aviation_in_date_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationproject",
            new_name="aviation_pr_project_07806d_idx",
            old_name="aviation_pr_project_idx",
        ),
    ]
