# Generated by Django 5.1.12 on 2025-11-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0002_rename_aviation_an_annotat_idx_aviation_an_annotat_b6722e_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviationannotation",
            name="aircraft_type",
            field=models.CharField(
                blank=True, default="", help_text="Type of aircraft involved", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="competency_indicators",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of selected competency indicators", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="crm_training_topics",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of CRM training topics", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_description",
            field=models.TextField(blank=True, default="", help_text="Detailed error description", null=True),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_management",
            field=models.CharField(
                blank=True, default="", help_text="How error was managed", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_outcome",
            field=models.CharField(
                blank=True, default="", help_text="Outcome of error", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_relevancy",
            field=models.CharField(
                blank=True, default="", help_text="Relevancy of error", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_training_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Auto-calculated training topics based on error selection",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_type_l1",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Error type level 1 category",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_type_l2",
            field=models.CharField(
                blank=True, default="", help_text="Error type level 2 category", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="error_type_l3",
            field=models.CharField(
                blank=True, default="", help_text="Error type level 3 category", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="event_labels",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of selected event labels", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="goals_to_achieve",
            field=models.TextField(
                blank=True, default="", help_text="Goals to achieve with training", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="likelihood",
            field=models.CharField(
                blank=True, default="", help_text="Likelihood assessment", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="notes",
            field=models.TextField(blank=True, default="", help_text="Additional notes", null=True),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="severity",
            field=models.CharField(
                blank=True, default="", help_text="Severity assessment", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_description",
            field=models.TextField(blank=True, default="", help_text="Detailed threat description", null=True),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_management",
            field=models.CharField(
                blank=True, default="", help_text="How threat was managed", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_outcome",
            field=models.CharField(
                blank=True, default="", help_text="Outcome of threat", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_training_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Auto-calculated training topics based on threat selection",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_type_l1",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Threat type level 1 category",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_type_l2",
            field=models.CharField(
                blank=True, default="", help_text="Threat type level 2 category", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="threat_type_l3",
            field=models.CharField(
                blank=True, default="", help_text="Threat type level 3 category", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="training_benefit",
            field=models.CharField(
                blank=True, default="", help_text="Potential training benefit", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="training_plan_ideas",
            field=models.TextField(blank=True, default="", help_text="Ideas for training plan", null=True),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_description",
            field=models.TextField(blank=True, default="", help_text="Detailed UAS description", null=True),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_management",
            field=models.CharField(
                blank=True, default="", help_text="How UAS was managed", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_relevancy",
            field=models.CharField(
                blank=True, default="", help_text="Relevancy of UAS", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_training_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Auto-calculated training topics based on UAS selection",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_type_l1",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UAS type level 1 category",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_type_l2",
            field=models.CharField(
                blank=True, default="", help_text="UAS type level 2 category", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aviationannotation",
            name="uas_type_l3",
            field=models.CharField(
                blank=True, default="", help_text="UAS type level 3 category", max_length=200, null=True
            ),
        ),
    ]
