# Generated by Django 5.1.12 on 2025-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0003_add_linked_result_to_labeling_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationevent",
            name="actual_landing_airport",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="aviationevent",
            name="arrival_airport",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="aviationevent",
            name="departure_airport",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
