# Generated by Django 5.1.12 on 2025-11-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0003_allow_null_optional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviationannotation",
            name="crm_training_topics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="CRM training topics grouped by category code",
                null=True,
            ),
        ),
    ]
