# Generated by Django 5.1.12 on 2025-12-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0004_aviationevent_actual_landing_airport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typehierarchy",
            name="category",
            field=models.CharField(
                choices=[
                    ("threat", "Threat"),
                    ("error", "Error"),
                    ("uas", "UAS"),
                    ("flight_phase", "Flight Phase"),
                    ("management", "Management"),
                    ("impact", "Impact"),
                    ("coping", "Coping"),
                    ("severity", "Severity"),
                    ("airport", "Airport"),
                    ("event_type", "Event Type"),
                    ("likelihood", "Likelihood"),
                    ("training_effect", "Training Effect"),
                    ("training_topics", "Training Topics"),
                ],
                max_length=50,
            ),
        ),
    ]
