# Generated by Django 5.1.12 on 2025-11-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0004_change_crm_topics_to_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationannotation",
            name="threat_capability",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Capability indicators for threat recognition",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aviationannotation",
            name="error_capability",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Capability indicators for error recognition",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aviationannotation",
            name="uas_capability",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Capability indicators for UAS recognition",
                null=True,
            ),
        ),
    ]
