# Generated by Django 5.1.12 on 2025-12-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0005_add_capability_fields"),
        ("aviation", "0005_rename_crm_training_topics_to_competency_selections"),
    ]

    operations = []
