# Generated by Django 5.1.12 on 2025-12-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0005_add_airport_and_other_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelingitem",
            name="error_relevance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Origin of error: 自发地, 来源于威胁, 来源于UAS T",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="labelingitem",
            name="uas_relevance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Origin of UAS: 来源于差错, 来源于威胁",
                max_length=50,
            ),
        ),
    ]
