# Generated by Django 5.1.12 on 2025-12-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0005_add_capability_fields"),
        ("aviation", "0006_add_relevance_fields"),
    ]

    operations = []
