# Generated by Django 5.1.12 on 2025-12-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0007_add_event_to_result_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelingitem",
            name="error_relevance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Origin of error: 来源于威胁",
                max_length=50,
            ),
        ),
    ]
