# Generated by Django 5.1 on 2025-12-26
# Manual migration for ReviewDecision and FieldFeedback models

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aviation', '0008_alter_labelingitem_error_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[
                        ('approved', 'Approved'),
                        ('rejected_partial', 'Rejected (Partial)'),
                        ('rejected_full', 'Rejected (Full)'),
                        ('revision_requested', 'Revision Requested'),
                    ],
                    help_text='Review decision status: approved, rejected_partial, rejected_full, or revision_requested',
                    max_length=20,
                )),
                ('reviewer_comment', models.TextField(
                    blank=True,
                    default='',
                    help_text='Optional comment from the reviewer explaining the decision',
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Timestamp when this review decision was made',
                )),
                ('labeling_item', models.ForeignKey(
                    help_text='The labeling item being reviewed',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='review_decisions',
                    to='aviation.labelingitem',
                )),
                ('reviewer', models.ForeignKey(
                    help_text='User who made this review decision',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='aviation_review_decisions',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'db_table': 'aviation_review_decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(
                    help_text='Name of the field being reviewed (e.g., threat_type_l1, error_management)',
                    max_length=50,
                )),
                ('feedback_type', models.CharField(
                    choices=[
                        ('partial', 'Partial'),
                        ('full', 'Full'),
                        ('revision', 'Revision'),
                    ],
                    help_text='Type of feedback: partial (some issues), full (completely incorrect), or revision (needs clarification)',
                    max_length=20,
                )),
                ('feedback_comment', models.TextField(
                    blank=True,
                    default='',
                    help_text='Detailed feedback explaining the issue with this field',
                )),
                ('reviewed_at', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Timestamp when this feedback was created',
                )),
                ('labeling_item', models.ForeignKey(
                    help_text='The labeling item this feedback refers to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='field_feedbacks',
                    to='aviation.labelingitem',
                )),
                ('review_decision', models.ForeignKey(
                    help_text='The review decision this feedback belongs to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='field_feedbacks',
                    to='aviation.reviewdecision',
                )),
                ('reviewed_by', models.ForeignKey(
                    help_text='User who provided this field feedback',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='aviation_field_feedbacks',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'db_table': 'aviation_field_feedback',
                'ordering': ['field_name'],
            },
        ),
    ]
