# Generated by Django 5.1.12 on 2025-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0009_reviewdecision_fieldfeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aviationproject",
            options={
                "permissions": [
                    (
                        "assign_aviation_project",
                        "Can Assign Aviation Project to other People",
                    ),
                    (
                        "assigned_to_aviation_project",
                        "User is assigned to Aviation Project",
                    ),
                ]
            },
        ),
        migrations.AlterField(
            model_name="fieldfeedback",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reviewdecision",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
