# Generated by Django 5.1.10 on 2025-07-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0054_add_brin_index_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": (("assign_task", "Assign task"),)},
        ),
    ]
