# Generated by Django 5.1.10 on 2025-07-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0055_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
    ]
