# Generated by Django 5.1.12 on 2025-09-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0056_alter_task_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRCharacterExtraction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(db_index=True, max_length=10)),
                ("confidence", models.FloatField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("image_width", models.IntegerField()),
                ("image_height", models.IntegerField()),
                ("page_number", models.IntegerField(db_index=True, default=1)),
                ("extraction_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_extractions",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "tasks_ocr_character_extraction",
                "ordering": ["page_number", "y", "x"],
                "indexes": [
                    models.Index(
                        fields=["task", "page_number"],
                        name="tasks_ocr_c_task_id_5a8c8b_idx",
                    )
                ],
            },
        ),
    ]
