# Generated by Django 5.1.12 on 2025-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("project_assigned", "Project Assigned"),
                    ("project_commented", "Project Task Commented"),
                    ("project_ocr_import", "Project OCR Import"),
                ],
                max_length=64,
            ),
        ),
        migrations.DeleteModel(
            name="NotificationTarget",
        ),
    ]
