# Generated by Django 5.1.12 on 2025-09-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFImageRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        help_text="Page number in the PDF document (1-indexed)"
                    ),
                ),
                (
                    "image_format",
                    models.CharField(
                        default="png",
                        help_text="Format of the extracted image",
                        max_length=10,
                    ),
                ),
                (
                    "resolution_dpi",
                    models.IntegerField(
                        default=300,
                        help_text="DPI resolution used for image extraction",
                    ),
                ),
                (
                    "extraction_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional parameters used during extraction",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the relationship was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the relationship was last updated",
                    ),
                ),
                (
                    "image_file",
                    models.ForeignKey(
                        help_text="Reference to the extracted image file upload",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_pdf",
                        to="data_import.fileupload",
                    ),
                ),
                (
                    "pdf_file",
                    models.ForeignKey(
                        help_text="Reference to the original PDF file upload",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_images",
                        to="data_import.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Image Relationship",
                "verbose_name_plural": "PDF Image Relationships",
                "db_table": "data_import_pdf_image_relationship",
                "ordering": ["pdf_file", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["pdf_file", "page_number"],
                        name="data_import_pdf_fil_25daf7_idx",
                    ),
                    models.Index(
                        fields=["image_file"], name="data_import_image_f_c7504b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="data_import_created_32c6f4_idx"
                    ),
                ],
                "unique_together": {("pdf_file", "page_number")},
            },
        ),
    ]
