# Generated by Django 5.1.12 on 2025-11-13 14:38

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0003_pdfimagerelationship"),
        ("projects", "0032_enhance_fileupload_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="When the file was uploaded",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["project", "-created_at"], name="fileupload_project_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["project", "user"], name="fileupload_project_user_idx"
            ),
        ),
    ]
