# Generated by Django 5.1.10 on 2025-07-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_auto_20241107_1031"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": [
                    ("assign_project", "Can Assign Project to other People"),
                    ("assigned_to_project", "User is assigned to the Project"),
                ]
            },
        ),
    ]
