# Generated by Django 5.1.10 on 2025-08-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_alter_project_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProxy",
            fields=[],
            options={
                "permissions": [
                    ("assign_project", "Can Assign Project to other People"),
                    ("assigned_to_project", "User is assigned to the Project"),
                ],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.project",),
        ),
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
    ]
