# Generated by Django 5.1.12 on 2025-10-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_projectproxy_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": [
                    ("assign_project", "Can Assign Project to other People"),
                    ("assigned_to_project", "User is assigned to the Project"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="projectproxy",
            options={},
        ),
    ]
