# Generated by Django 5.1.12 on 2025-11-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_alter_project_options_alter_projectproxy_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectProxy",
        ),
    ]
