export const PERMISSIONS = {
  ORGANIZATIONS_CREATE: 'organizations.create',
  ORGANIZATIONS_VIEW: 'organizations.view',
  ORGANIZATIONS_CHANGE: 'organizations.change',
  ORGANIZATIONS_DELETE: 'organizations.delete',
  ORGANIZATIONS_INVITE: 'organizations.invite',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_VIEW: 'projects.view',
  PROJECTS_CHANGE: 'projects.change',
  PROJECTS_DELETE: 'projects.delete',
  PROJECTS_ASSIGN: 'projects.assign_project',
  TASKS_CREATE: 'tasks.create',
  TASKS_VIEW: 'tasks.view',
  TASKS_CHANGE: 'tasks.change',
  TASKS_DELETE: 'tasks.delete',
  ANNOTATIONS_CREATE: 'annotations.create',
  ANNOTATIONS_VIEW: 'annotations.view',
  ANNOTATIONS_CHANGE: 'annotations.change',
  ANNOTATIONS_DELETE: 'annotations.delete',
  ACTIONS_PERFORM: 'actions.perform',
  PREDICTIONS_ANY: 'predictions.any',
  AVATAR_ANY: 'avatar.any',
  LABELS_CREATE: 'labels.create',
  LABELS_VIEW: 'labels.view',
  LABELS_CHANGE: 'labels.change',
  LABELS_DELETE: 'labels.delete',
  MODELS_CREATE: 'models.create',
  MODELS_VIEW: 'models.view',
  MODELS_CHANGE: 'models.change',
  MODELS_DELETE: 'models.delete',
  MODEL_PROVIDER_CONNECTION_CREATE: 'model_provider_connection.create',
  MODEL_PROVIDER_CONNECTION_VIEW: 'model_provider_connection.view',
  MODEL_PROVIDER_CONNECTION_CHANGE: 'model_provider_connection.change',
  MODEL_PROVIDER_CONNECTION_DELETE: 'model_provider_connection.delete',
  WEBHOOKS_VIEW: 'webhooks.view',
  WEBHOOKS_CHANGE: 'webhooks.change',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export type UserRole = 'Annotator' | 'Researcher' | 'Manager';